### ISSUE TITLE
Porting

### ISSUE THREAD

**Issue by gatalec** [mnit-rtmc/ntcip#1]
This is a great project. I have questions about NTCPIP. How can we DM?

**Comment by DougLau** [comment]
I don't think github has a DM feature.  What are you interested in porting?

**Comment by gatalec** [comment]
I need to interface to a TCPIP DMS system using C/C++.

**Comment by DougLau** [comment]
Depending on what you need, that might be easy with [cbindgen](https://github.com/mozilla/cbindgen).

**Comment by DougLau** [comment]
Feel free to reopen if you have any more questions.
