### ISSUE TITLE
Unable to add a valid Graphic into the GraphicTable

### ISSUE THREAD

**Issue by Fahad-Anwar3** [mnit-rtmc/ntcip#2]
I am trying to add a Graphic to the GraphicTable. the graphic is of type .gif. It gives an error when I call the function 

```rust
let mut graphics = GraphicTable::default();
let g = graphics.graphic_mut(24).unwrap();
```

I got this snippet from the library to ensure I am not making any mistakes. The error is

_thread 'actix-rt|system:0|arbiter:0' panicked at src/utils/helpers.rs:101:37:
called `Option::unwrap()` on a `None` value_

I am trying to input the graphic at slot number 24 and I am unable to get a reference to any slot at all and not just 24, I tried with slot number 0 and 200 too but it's the same error every time. below is the exact code 

```rust
    let mut graphics = GraphicTable::default();
    let g = graphics.graphic_mut(24).unwrap();
    if let Some(g) = graphics.graphic_mut(24) {
        eprintln!("Reference to graphic slot 24 obtained successfully.");
        *g = graphic.clone();
        eprintln!("Graphic inserted at index 24");
    } else {
        eprintln!("Failed to obtain reference to graphic slot 24.");
    }
```
    
The below function converts the input image into a Graphic 
    
```rust
pub fn load_graphic<R: Read>(reader: R, number: u8) -> Result<Graphic> {
    // load the first step only
    match Decoder::new(reader).into_steps().next() {
        Some(step) => {
            let step = step?;
            let name = FStr::from_str_lossy(&format!("G{number}"), 0);
            let raster: Raster<SBgr8> = Raster::with_raster(step.raster());
            let height = raster.height().try_into().unwrap();
            let width = raster.width().try_into().unwrap();
            let transparent_color = step.transparent_color().map(|_c| Color::Rgb(0, 0, 0));
            let slice: Box<[u8]> = raster.into();
            let bitmap: Vec<u8> = slice.into();
            Ok(Graphic {
                number,
                name,
                height,
                width,
                gtype: ColorScheme::Color24Bit,
                transparent_color,
                bitmap,
            })
        }
        None => Err(Error::MissingGraphic),
    }
}
```

@DougLau Can you please help me with the issue? Please let me know if you need additional details

**Comment by DougLau** [comment]
Note that both `graphic` and `graphic_mut` take the **graphic number** as a parameter, not the slot / index.  In a default `GraphicTable`, all graphic numbers are 0, indicating empty rows.

If 0 is also not working, maybe the `GraphicTable` has no entries?  If not specified, the const generic parameter `G` will normally be inferred.  You may need to specify it in the declaration.

```rust
let mut graphics: GraphicTable<24> = GraphicTable::default();
if let Some(g) = graphics.graphic_mut(graphic.number) {
    *g = graphic;
} else if let Some(g) = graphics.graphic_mut(0) {
    *g = graphic;
} else {
    panic!("No available slots!");
}
```

**Comment by Fahad-Anwar3** [comment]
Thank you for your help Doug. It worked!
